# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/acd89628-ba7f-4cd3-87c2-af8886e45a5d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-469425d4-47be-40a4-82db-0f2b5c3e8da9".device = "/dev/disk/by-uuid/469425d4-47be-40a4-82db-0f2b5c3e8da9";
  boot.initrd.luks.devices."luks-b47f9ddf-a89a-4185-b399-66cf23d2049b".device = "/dev/disk/by-uuid/b47f9ddf-a89a-4185-b399-66cf23d2049b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7688-9ADB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/edaa66eb-4557-40ad-9245-88124c62f0d8"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
